server:
     port: 8081
person:
     lastName: Zhangsan
     age: 22
     birthday: 2018/12/20
     boss: false
     maps: {k1: k1,K2: 22}
     lists:
        - lisi
        - zhaoliu
        - wangwu
     dogs: {name: wangcai,age: 8}